import streamlit as st
from utils import get_session, calculate_late_fee, generate_invoice_bytes
from models import Rental
from datetime import datetime, timezone

def show():
    if 'user' not in st.session_state or not st.session_state.user:
        st.error("Please login first")
        return

    st.title("📖 My Rentals")

    session = get_session()
    user = st.session_state.user

    rentals = session.query(Rental).filter_by(user_id=user.id).order_by(Rental.rent_date.desc()).all()

    for rental in rentals:
        late_fee = (rental.late_fee or 0) if rental.return_date else calculate_late_fee(rental)
        with st.expander(f"📖 {rental.book.title} — {rental.status.upper()}"):
            st.write(f"**Author:** {rental.book.author}")
            st.write(f"**Rent Date:** {rental.rent_date.strftime('%Y-%m-%d')}")
            st.write(f"**Due Date:** {rental.due_date.strftime('%Y-%m-%d')}")
            st.write(f"**Total Amount:** ${rental.total_amount:.2f}")
            if rental.return_date:
                st.write(f"**Return Date:** {rental.return_date.strftime('%Y-%m-%d')}")
                if late_fee > 0:
                    st.write(f"**Late Fee:** ${late_fee:.2f}")
            if rental.status == "active":
                if st.button("Return Book", key=f"return_{rental.id}"):
                    try:
                        rental.return_date = datetime.now(timezone.utc)
                        rental.status = "returned"
                        rental.late_fee = calculate_late_fee(rental)
                        rental.book.available += 1
                        session.commit()
                        st.success("Book returned!")
                        st.rerun()
                    except Exception as e:
                        session.rollback()
                        st.error(f"Could not return book: {str(e)}")
            # Invoice download: show download button with pre-generated bytes if this rental was requested
            if st.session_state.get("invoice_rental_id") == rental.id and st.session_state.get("invoice_bytes"):
                st.download_button(
                    label="⬇️ Download Invoice (PDF)",
                    data=st.session_state.invoice_bytes,
                    file_name=f"invoice_rental_{rental.id}.pdf",
                    key=f"download_{rental.id}",
                    mime="application/pdf",
                )
                if st.button("Cancel", key=f"cancel_invoice_{rental.id}"):
                    del st.session_state.invoice_rental_id
                    del st.session_state.invoice_bytes
                    st.rerun()
            else:
                if st.button("Download Invoice", key=f"invoice_{rental.id}"):
                    try:
                        pdf_bytes = generate_invoice_bytes(rental)
                        st.session_state.invoice_rental_id = rental.id
                        st.session_state.invoice_bytes = pdf_bytes
                        st.rerun()
                    except Exception as e:
                        st.error(f"Error generating invoice: {str(e)}")

    session.close()
